services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblioteca
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py collectstatic --no-input &&
             python3 manage.py migrate &&
             python3 manage.py create_admin_user &&
             python3 manage.py runserver 0.0.0.0:8000"
