# Generated by Django 5.1.7 on 2025-03-24 23:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.CharField(max_length=100)),
                ('turma', models.CharField(choices=[('1A', '1º ADMNISTRAÇÃO'), ('1E', '1º ENFERMAGEM'), ('1I', '1º INFORMÁTICA'), ('1L', '1º LOGISCA'), ('2A', '2º ADMNISTRÇÃO'), ('2E', '2º ENFERMAGEM'), ('2DS', '2º DESENVOLVIMENTO'), ('2L', '2º LOGISCA'), ('3A', '3º ADMNISTRAÇÃO'), ('3E', '3º ENFERMAGEM'), ('3DS', '3º DESENVOLVIMENTO'), ('3I', '3º INFORMATICA')], max_length=100)),
                ('data_emprestimo', models.DateField(verbose_name=django.utils.timezone.now)),
                ('data_devolucao', models.DateField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
