# Generated by Django 5.1.7 on 2025-03-25 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_loan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['data_devolucao'], 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AddField(
            model_name='loan',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='data_emprestimo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
