# Generated by Django 5.1.7 on 2025-03-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_loan_options_loan_devolvido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='livro',
            field=models.CharField(max_length=200),
        ),
    ]
