# Generated by Django 5.1.7 on 2025-03-26 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_loan_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
