# Generated by Django 5.1.7 on 2025-03-26 23:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_loan_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='editora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='aluno',
            field=models.CharField(max_length=100, verbose_name='Aluno(a)'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='data_devolucao',
            field=models.DateField(verbose_name='Data de Devolução'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='data_emprestimo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Empréstimo'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='devolvido',
            field=models.BooleanField(default=False, verbose_name='Devolvivo?'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Livro'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='turma',
            field=models.CharField(choices=[('1A', '1º ADMNISTRAÇÃO'), ('1E', '1º ENFERMAGEM'), ('1I', '1º INFORMÁTICA'), ('1L', '1º LOGISCA'), ('2A', '2º ADMNISTRÇÃO'), ('2E', '2º ENFERMAGEM'), ('2DS', '2º DESENVOLVIMENTO'), ('2L', '2º LOGISCA'), ('3A', '3º ADMNISTRAÇÃO'), ('3E', '3º ENFERMAGEM'), ('3DS', '3º DESENVOLVIMENTO'), ('3I', '3º INFORMATICA')], max_length=100, verbose_name='Turma'),
        ),
    ]
