name: Continuous Integration in Django application with Deployment to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy_sistema_biblioteca:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo su

          # Acessa o diretório do projeto
          cd /var/www/sistema-biblioteca || { echo "Falha ao acessar diretório"; exit 1; }
          
          # Configurações de segurança do Git
          sudo git config --global --add safe.directory /var/www/sistema-biblioteca
          sudo git config --global pull.rebase false  # Define estratégia de merge padrão
          
          # Corrige permissões
          sudo chown -R ${{ secrets.EC2_USERNAME }}:${{ secrets.EC2_USERNAME }} .
          sudo find . -type d -exec chmod 755 {} \;  # Permissões para diretórios
          sudo find . -type f -exec chmod 644 {} \;  # Permissões para arquivos
          
          # Permissões especiais para o diretório de workflows
          sudo chmod -R 775 .github/workflows/
          
          # Executa o script de atualização
          chmod +x ./update-image.sh
          ./update-image.sh || { echo "Falha na execução do update-image.sh"; exit 1; }