name: Continuous Integration in Django application with Deployment to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy_sistema_biblioteca:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo su

          # Acessa o diretório do projeto
          cd /var/www/sistema-biblioteca || { echo "Falha ao acessar diretório"; exit 1; }
          sudo chown -R $(whoami) .
          
          # Executa o script de atualização
          chmod +x ./update-image.sh
          ./update-image.sh || { echo "Falha na execução do update-image.sh"; exit 1; }